### ISSUE TITLE
Yeast.yeast() is not thread safe

### ISSUE THREAD

**Issue by trinopoty** [socketio/engine.io-client-java#100]
`Yeast.yeast()` is not thread safe. If two thread calls it almost simultaneously, it is prone to returning same value.
I don't know how this problem has not surfaced till date but in the socket.io java server project, this is causing problems like two distinct connections getting the same id.
Also, as a side note, `Yeast.yeast()` uses `new Date()` every time which may cause problems if called frequently (memory wastage).

Can you please fix this issue and update the library.

**Comment by darrachequesne** [comment]
Hi @trinopoty, sorry for the delay on this issue.

> this is causing problems like two distinct connections getting the same id

If I'm not mistaken, the string created by yeast is used in the query params, to prevent a proxy from caching the response of the server. Are you suggesting it does happen when sending several HTTP requests in a row?

Note: in the JS server, the session ID (`sid` in the query param) is generated by the `base64id` module [here](https://github.com/socketio/engine.io/blob/4.0.5/lib/server.js#L220)

**Comment by trinopoty** [comment]
Yeast is using `new Date().getTime()` to generate a session id. On the server library, this was causing issues where two unrelated connections got the same `sid` because they came in at around the same time. I switched it over to an `AtomicLong` based implementation.
From the looks of it, this will not be too much of a problem in this library since it does not generate `sid`.

**Comment by darrachequesne** [comment]
Oh ok, thanks for the explanation!

That being said, the `yeast()` method is indeed not thread safe, which might cause some problems when creating several java clients (during load tests, for example).
