### ISSUE TITLE
WARNING: Dependency org.json:json:20090211 is ignored for debug

### ISSUE THREAD

**Issue by JTallis** [socketio/engine.io-client-java#13]
I recently found this repository and so I added the compile statement to my build.gradle and it creates these warnings on debug:

WARNING: Dependency org.json:json:20090211 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
WARNING: Dependency org.json:json:20090211 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages

I'm running android 4.4.4 on my device.

**Comment by nkzawa** [comment]
Yeah, I know that but we can't remove the dependency since this library is not only for Android.
Anyway I believe there is no problem with functionality though it's annoying.
Do you know a good way to suppress these warnings?

**Comment by JTallis** [comment]
I don't know a way to suppress the warnings however would it be possible to check if the OS being ran is android and to do something else?

**Comment by mdellerie** [comment]
You can exclude json dependency from the module by adding the following lines in your build.gradle : 

compile ('com.github.nkzawa:socket.io-client:0.4.1'){
        exclude group: 'org.json', module: 'json'
}

This worked for me : no warning anymore :)

**Comment by heinhtetaung92** [comment]
Thanks mdellerie, 
That works for me too. Thanks for answer. :)

**Comment by mdellerie** [comment]
You're welcome! ;-)

**Comment by alemures** [comment]
I was getting those annoying warnings as well and it solved my problem, thanks @mdellerie !

**Comment by mdellerie** [comment]
my pleasure ! ;)

**Comment by akamadya** [comment]
wow, thank's

**Comment by binhtvt** [comment]
Thank you @mdellerie  :+1:

**Comment by nkzawa** [comment]
Added to README. Thanks, @mdellerie !

**Comment by MikeSoft** [comment]
thanks @mdellerie

**Comment by Chheata** [comment]
@mdellerie  I use this 
compile 'org.json:json:20151123'

and after I add this 
compile 'com.github.nkzawa:socket.io-client:0.3.0'{
        exclude group: 'org.json', module: 'json'
    }

it still not work 😢😥

**Comment by vishaljadav24** [comment]
@Chheata  Use this: 
  compile ('com.github.nkzawa:socket.io-client:0.4.1'){
exclude group: 'org.json', module: 'json'
}

It's works for me. Thanks @mdellerie

**Comment by MuhammadjonTohirov** [comment]
try to use this library.
    compile 'org.json:org.json:chargebee-1.0'

**Comment by ladykat** [comment]
Hi guys! 
I tried to use this: compile ('com.github.nkzawa:socket.io-client:0.4.1'){
exclude group: 'org.json', module: 'json'
}

But doesn't work too!

Error message as follows, help please?
Error:Could not find method compile() for arguments [com.github.nkzawa:socket.io-client:0.4.1, build_cunlaeueny2t2ajmdz9zk0q17$_run_closure7@31411f8f] on project ':android' of type org.gradle.api.Project.

**Comment by DanChab** [comment]
Many thanks, worked for me

**Comment by serrokitskiy** [comment]
@ladykat You must add comma))) 
**replace** 
compile 'com.github.nkzawa:socket.io-client:0.4.1' {
        exclude group: 'org.json', module: 'json'
    }
**to**
compile 'com.github.nkzawa:socket.io-client:0.4.1'**,** {
        exclude group: 'org.json', module: 'json'
    }

**Comment by wajdan846** [comment]
great thanks mdellerie

**Comment by silentcontrol00** [comment]
@serrokitskiy Hay Bro,thank alot for your answer.
it work for me Bro.

**Comment by Daksh23** [comment]
Warning:WARNING: Dependency org.json:json:20140107 is ignored for withAnalyticsDebug as it may be conflicting with the internal version provided by Android. how to solve this
???????????

**Comment by RishabhS05** [comment]
thanks ....: )

**Comment by Masoud2159** [comment]
Hi!
I tried to use this:
 dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        compile 'com.github.nkzawa:socket.io-client:0.4.1', {
            exclude group: 'org.json', module: 'json'
        }

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

But doesn't work!

Error message as follows, help, please?

Could not find method compile() for arguments [com.github.nkzawa:socket.io-client:0.4.1, build_7vmonel3c4y8lhnndnc10z8wh$_run_closure1$_closure3$_closure4@388f4cb] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
