### ISSUE TITLE
Issue with checksum generated by Artifactory for engine.io pom

### ISSUE THREAD

**Issue by sthang** [socketio/engine.io-client-java#25]
For our project we wanted to upgrade socket.io-client.java from 0.4.* to 0.5.2. On doing that the artifactory had trouble downloading the pom file of engine.io-client.java. The repo1.maven.org from which the files are downloaded has setting to generate Checksum if missing. Apparently the checksum generated by Artifactory does not match the checksum related to engine.io-client pom for version 0.5.1. 

{
  "errors" : [ {
    "status" : 409,
    "message" : "Rejected artifact download request: Checksum policy 'GEN_IF_ABSENT' rejected the artifact 'repo1-cache:com/github/nkzawa/engine.io-client/0.5.1/engine.io-client-0.5.1.pom'. rest of the message is hidden since it reveals checksum details.
}

Question:

1. is the mapping right between socket.io(0.5.2) and engine.io(0.5.1) clients?
2. Who generates the checksum and what contributes to it?

**Comment by nkzawa** [comment]
> is the mapping right between socket.io(0.5.2) and engine.io(0.5.1) clients?

yes, socket.io-client 0.5.2 has a dependency to engine.io-client 0.5.1, see https://github.com/nkzawa/socket.io-client.java/blob/master/pom.xml#L61 .

> Who generates the checksum and what contributes to it?

I'm not sure about the checksum, but the artifacts is released by using maven release plugin.
