### ISSUE TITLE
EngineIOException: xhr poll error

### ISSUE THREAD

**Issue by theasmoth** [socketio/engine.io-client-java#31]
trying to add cookie to headers

I/SOCKET﹕ ERROR io.socket.engineio.client.EngineIOException: xhr poll error

compile 'io.socket:socket.io-client:0.6.1'
compile 'io.socket:engine.io-client:0.6.1'

server nodejs socket.io 1.3.5

```code
        opts = new Socket.Options();
        opts.host = "http://192.168.0.12";
        opts.port = 3030;
        socket = new Socket(opts);
//        socket.setDefaultHostnameVerifier(new HostnameVerifier() {
//            @Override
//            public boolean verify(String hostname, SSLSession session) {
//                return true;
//            }
//        });
        socket.on(Socket.EVENT_TRANSPORT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Transport transport = (Transport)args[0];
                transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        @SuppressWarnings("unchecked")
                        Map<String, List<String>> headers = (Map<String, List<String>>) args[0];
                        headers.put("Cookie", Arrays.asList(authCookie));
                        //Log.i("SOCKET", String.valueOf(headers.size()));
                    }
                });
            }
        });
        socket.on(Socket.EVENT_ERROR, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i("SOCKET", "ERROR " + String.valueOf(args[0]));
            }
        });
        socket.open();
```

**Comment by theasmoth** [comment]
my mistake
host string with "http://"

**Comment by Rishabh-sx** [comment]
This will fix the issue:
/**
     * To get socket single instance.
     *
     * @return socket instance
     */
    public Socket getSocket() {
        if (mSocket != null)
            return mSocket;
        else {
            try {
                HostnameVerifier myHostnameVerifier = new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        return true;
                    }
                };
                SSLContext mySSLContext = SSLContext.getInstance("TLS");
                TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
                    public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                        return new java.security.cert.X509Certificate[]{};
                    }

                    public void checkClientTrusted(X509Certificate[] chain,
                                                   String authType) throws CertificateException {
                    }

                    public void checkServerTrusted(X509Certificate[] chain,
                                                   String authType) throws CertificateException {
                    }
                }};

                mySSLContext.init(null, trustAllCerts, new java.security.SecureRandom());

                OkHttpClient okHttpClient = new OkHttpClient.Builder()
                        .hostnameVerifier(myHostnameVerifier)

                        .sslSocketFactory(mySSLContext.getSocketFactory(), new X509TrustManager() {
                            @Override
                            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {

                            }

                            @Override
                            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {

                            }

                            @Override
                            public X509Certificate[] getAcceptedIssuers() {
                                return new X509Certificate[0];
                            }
                        })
                        .build();


                // HttpsURLConnection.setDefaultHostnameVerifier(myHostnameVerifier);
                IO.Options options = new IO.Options();
                //options.webSocketFactory = okHttpClient;
                //options.secure = true;
                //options.transports = new String[]{WebSocket.NAME};
                //options.reconnection = true;
                //options.forceNew = true;
                options.callFactory = okHttpClient;
                options.webSocketFactory = okHttpClient;
                options.query = "authtoken=" + AppSharedPrefrence.getString(this, AppSharedPrefrence
                        .AUTH_TOKEN)
                        + "&Lang=" + (AppSharedPrefrence.
                        getString(this, AppSharedPrefrence.LANGUAGE).
                        equalsIgnoreCase(AppConstant.ENGLISH)
                        ? AppConstant.ENGLISH : AppConstant.ARABIC);


                mSocket = IO.socket(SocketConstants.SOCKET_URL, options);
                mSocket.connect();
            } catch (URISyntaxException e) {
                throw new RuntimeException(e);
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            } catch (KeyManagementException e) {
                e.printStackTrace();
            }

        }
        return mSocket;

    }

**Comment by EduardoDornel** [comment]
@Rishabh-sx thanks!!
