### ISSUE TITLE
socket with channel, xhr poll error

### ISSUE THREAD

**Issue by lugaid13** [socketio/engine.io-client-java#33]
I have created a simple Java app.
I'm connecting to a socket using the following URL pattern
<code>
String url = "http://host:port/channel";
socket = new Socket(url);
</code>
But I am getting the Xhr poll error, and I have not found any help because none of the examples use a url that specifies something after the port.
<code>
io.socket.engineio.client.EngineIOException: xhr poll error
</code>
Please help, I can provide code if needed.

**Comment by nkzawa** [comment]
Maybe you need to set `path` option?

**Comment by oliverhausler** [comment]
related with https://github.com/socketio/socket.io-client-java/issues/250

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by cliffordyohannan** [comment]
Hi, i have similar issue only in  android 4.4 version

**Comment by oliverhausler** [comment]
The problem exists in 4.4 as well, yes. It works better than 4.2 but not stable.

**Comment by cliffordyohannan** [comment]
@oliverhausler any solution?

**Comment by VicV** [comment]
Still an issue in 4.4
