### ISSUE TITLE
No action in Desktop client

### ISSUE THREAD

**Issue by voidstarfire** [socketio/engine.io-client-java#34]
I was using io.socket:socket.o-client:0.6.1 which works on Desktop & Android but not iOS because of this issue: 

https://github.com/robovm/robovm/issues/1153

Now I've tried download SocketIO but it is mostly made up of 
https://github.com/socketio/socket.io-client-java 
but when trying this library it completely fails on all devices. (Doesn't respond to anything or throw any errors).

My main issue/confusion is

What's the main different between 

https://github.com/socketio/socket.io-client-java (Working on everything except iOS = java.lang.IllegalArgumentException: unexpected url)
& 
https://github.com/socketio/engine.io-client-java (Works on nothing but supplies socket.o-client-java)

I can't seem to get either of them working fully.

My main issue is what is https://github.com/socketio/socket.io-client-java doing that makes it work on everything but iOS that this library is doing so it works on nothing?

**Comment by nkzawa** [comment]
Do you mean socket.io-client works but engine.io-client doesn't do for you ? It sounds weird since socket.io-client-java internally uses engine.io-client-java.

**Comment by voidstarfire** [comment]
That's exactly what I'm saying. Yes you can see in the robovm/robovm#1153 there is a test project that shows this. Simple compile socket engine instead of socket-io.

I've been trying to figure this out for over a month now.

**Comment by nkzawa** [comment]
> OLLY:LOG: Connecting with server: http://192.168.1.11:9999
> java.lang.IllegalArgumentException: unexpected url: http://192.168.1.11:9999/socket.io/? EIO=3&sid=3x4xcfIDbrYeX7RlAAAH&transport=websocket
>         at com.squareup.okhttp.Request$Builder.url(Request.java:153)

It looks the error was thrown in [okhttp](https://github.com/square/okhttp) rather than socket.io-client-java.

**Comment by voidstarfire** [comment]
I tried various versions of okhttp (downloading the library and trying to run it directly) but failed. Any idea how i'd fix it?

**Comment by voidstarfire** [comment]
Also SocketEngine still doesn't work when replacing SocketIO Java. Even though it's almost the same.

**Comment by nkzawa** [comment]
Socket.io (engine.io too) creates a thread with `io.socket.thread.EventThread` and run most codes in it.   
That might be related but otherwise I have no idea. Anyway I believe this should be the problem of robovm.

**Comment by voidstarfire** [comment]
Ah yes but SocketEngine fails on Android & Desktop not just RoboVM. While Socket.Java works.

**Comment by nkzawa** [comment]
Umm weird. Does your app run on normal jdk? Can you post your code of engine.io if possible?

**Comment by voidstarfire** [comment]
You can download a test case here
https://github.com/voidstarfire/LibGDX-SocketIO-with-Node/tree/master

Then change the root build to compile for each library.

**Comment by nkzawa** [comment]
Need more instruction. Where is the app code for engine.io ?

**Comment by voidstarfire** [comment]
SocketIO Java: https://github.com/socketio/socket.io-client-java
EngineIO https://github.com/socketio/engine.io-client-java

The code within the app is almost identical but with different enums.

```
I.E: Socket.EVENT_DISCONNECT
Would be: Socket.EVENT_CLOSE
```

**Comment by nkzawa** [comment]
They are different libraries. It doesn't work if you didn't change the code.

**Comment by voidstarfire** [comment]
I'm using the most basic connection method which is almost identical and it fails for SocketEngineIO. I can include the code and update the repo if you want?

**Comment by nkzawa** [comment]
Yes please. And server implementation too.

**Comment by voidstarfire** [comment]
Theres a server example within the app, within the server directory. Use NPM install and run with node.
You can switch between EngineIO and SocketIO in Desktop class.

**Comment by nkzawa** [comment]
I mean I have to check actual code you tried. Otherwise I can't help you.

**Comment by voidstarfire** [comment]
You can find and run the code here: https://github.com/voidstarfire/LibGDX-SocketIO-with-Node/tree/master

But the actual code is:
For SocketIOJava

```
@Override
            public boolean tap(float x, float y, int count, int button)
            {
                if(socket == null)
                {
                    try
                    {
                        log("Beginning connection with SocketIO server.");

                        //TODO Replace with you're local host IP on the router.
                        //socket = IO.socket("http://127.0.0.1:3001");
                        socket = IO.socket("http://192.168.1.11:3001");

                        socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

                            @Override
                            public void call(Object... args) {
                                log("Connected with server.");
                                socket.emit("test", "Hi, we connected!");
                            }
                        })
                        .on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

                            @Override
                            public void call(Object... args) {
                                socket = null;
                            }

                        });

                        socket.connect();
                    }
                    catch (Exception exception)
                    {
                        log("Disconnected with server.");
                        exception.printStackTrace();
                    }
                }
                else
                {
                    socket.emit("test", "Test message: " + String.valueOf(sentItems));
                    sentItems++;
                }



                return true;
            }
```

For SocketEngineIO

```
                if(socket == null)
                {
                    try
                    {
                        log("Beginning connection with SocketIO server.");

                        //TODO Replace with you're local host IP on the router.
                        //socket = IO.socket("http://127.0.0.1:3001");
                        socket = new Socket("http://127.0.0.1:3001");

                        socket = new Socket("ws://localhost");
                        socket.on(Socket.EVENT_OPEN, new Emitter.Listener() {
                            @Override
                            public void call(Object... args) {
                                socket.send("hi");
                                socket.close();
                            }
                        });
                        socket.open();

                    }
                    catch (Exception exception)
                    {
                        log("Disconnected with server.");
                        exception.printStackTrace();
                    }
                }
                else
                {
                    socket.emit("test", "Test message: " + String.valueOf(sentItems));
                    sentItems++;
                }
```

The node server code:

```
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function(req, res){
  res.send('<h1>LibGDX SocketIO client to NodeJS server test, up and running!</h1>');
});

io.on('connection', function(socket)
{
    console.log('a user connected');
    console.log('Socket Object: ' + socket);

    socket.on('test', function(msg)
    {
        console.log(msg);
    });


    socket.on('disconnect', function(msg)
    {
        console.log('Client disconnected with message: ' + msg);
    });

});

http.listen(3001, function(){
  console.log('listening on *:3001');
});
```

**Comment by nkzawa** [comment]
Thanks. Do you mean you used `server.js` without modifyng it for engine.io?

**Comment by voidstarfire** [comment]
Yes because it's the standard way to setup a socket-io server.

**Comment by nkzawa** [comment]
That's the cause. You have to use engine.io server. Socket.io server doesn't work with engine.io-client.

**Comment by voidstarfire** [comment]
I see, that is JAVA only?

**Comment by nkzawa** [comment]
no. nodejs client is also the same.

**Comment by voidstarfire** [comment]
Thanks for the info, so what is EngineIO doing differently to SocketIO?

**Comment by nkzawa** [comment]
they have different protocol. socket.io is based on engine.io though.

**Comment by voidstarfire** [comment]
I did some tests with EngineIO server.

Successful on Desktop & Android.
Fails on iOS.
