### ISSUE TITLE
Disconnect in  a few seconds!

### ISSUE THREAD

**Issue by siyehua** [socketio/engine.io-client-java#35]
Disconnect in a few seconds after I connect the service!
Why? What need me setting?
And I found it disconnect in 10 seconds.

**Comment by nkzawa** [comment]
Maybe the same issue with https://github.com/socketio/engine.io-client-java/issues/32

**Comment by siyehua** [comment]
@nkzawa Thanks.

**Comment by ZeroBrain** [comment]
@siyehua Okhttp 2.5 was added default timeout.
but enginio supported okhttp 2.4.

Recently, engine-io 0.6.2.Snapshot would support Okhttp 2.5 and default timeout.

so, I'm waiting for supporting Okhttp 2.5 and engine-io & socket.io 0.6.2.

**Comment by siyehua** [comment]
@ZeroBrain Thank you.nkazwa has already repaired this BUG in the latest commit.[#32](https://github.com/socketio/engine.io-client-java/commit/09741541812ddedc86622bd50b83b42d2974dd6c)

**Comment by ZeroBrain** [comment]
@siyehua yes. :+1:

**Comment by nkzawa** [comment]
Thank you guys for your patience. I will release it soon.

**Comment by nkzawa** [comment]
0.6.2 is out.
