### ISSUE TITLE
Problem with connections through proxy

### ISSUE THREAD

**Issue by jldevelops** [socketio/engine.io-client-java#37]
Hi, I have an android app which was connected to socket io server(node.js).

Recently I have switched server to netty-socketio and updated to socket.io-client-java last version, and I noticed all clients running through proxy can´t connect.

Tried with 0.4.2 and works fine, but not with 0.5.0 and next versions. Seems to be a problem with okhttp-ws, but I didn´t find any errors on engine-io-client-java impl. Could be a problem related to okhttp-ws too, but I think it´s less probable -althrough I didn´t review okhttp-ws code-.

Is this an issue or I forbid something? If it is, how I could help to fix it?

**Comment by nkzawa** [comment]
Umm, I have no idea. Any error logs or something?

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen.
