### ISSUE TITLE
0.6.2 still requires OkHttp 2.5.0

### ISSUE THREAD

**Issue by inktomi** [socketio/engine.io-client-java#41]
I see that https://github.com/socketio/engine.io-client-java/commit/c8bdd27b4596f1ee365b1ebebcfd81e3114ebddc made changes to work with OkHttp 2.7.0, however the released POM still pulls in 2.5.0 as it hasn't yet been updated. 

OkHttp-WS 2.5.0 is incompatible with OkHttp 2.7.0, meaning that apps which use your project - even as a transitive dependency - cannot upgrade to OkHttp 2.7.0 until SocketIO releases a fix.

**Comment by nkzawa** [comment]
v0.6.3 has been released :)

**Comment by inktomi** [comment]
Thank you! :smile:
