### ISSUE TITLE
Is there an API upgrade guide?

### ISSUE THREAD

**Issue by gradha** [socketio/engine.io-client-java#50]
I'm on a project with version 0.5.2 and would like to upgrade to 0.7.0. Some API changes are reflected in the readme but there are others which can't be inferred from the javadocs. Is there a guide somewhere? One problematic API example would be the Socket.connected() method which doesn't exist in 0.7.0 any more.

**Comment by nkzawa** [comment]
Unfortunately, there is no specific guide for upgrade. Please read `History.md` and `README.md`.
btw, I believe `Socket#connected()` still exists().
