### ISSUE TITLE
what different engine.io-client-java with socket.io-client-java ?

### ISSUE THREAD

**Issue by JoneWeng** [socketio/engine.io-client-java#58]
what  different ? 

i want to develop android realtime push service?

**Comment by nkzawa** [comment]
For engine.io, please see https://github.com/socketio/engine.io, `engine.io-client-java` is a client of it.

engine.io is a simple communication channel, but socket.io has a lot more features like namespaces, rooms and reconnection. engine.io is internally used in socket.io as the communication layer.
