### ISSUE TITLE
Publish new release with updated OkHttp3 version

### ISSUE THREAD

**Issue by VicV** [socketio/engine.io-client-java#67]
Its been in the code for roughly 20 days but we are still waiting on an actual release.

This has become absolutely necessary as clients who include socketio as well as the most recent version of okttp3 will see crashes.

**Comment by MNDaveC** [comment]
+1

**Comment by ClaytonBlack** [comment]
+1

**Comment by manjunathc23** [comment]
+1

**Comment by nkzawa** [comment]
released!
