### ISSUE TITLE
Failed polling transport kills websocket transport

### ISSUE THREAD

**Issue by hiredman** [socketio/engine.io-client-java#76]
Hello, 

I am indirectly a user of engine.io-client-java via socket.io-client-java. I have a server that for reasons which I hope to rectify later fails to correctly respond to the requests the polling transport makes. When the socket.io-client-java library is setup to only use websockets it is able to connect to the server just fine. If I leave the default set of transport in place (polling and websockets) the client fails to successfully connect. 

What appears to happen (from the logs) is engine.io-client-java starts both the websocket and the polling transport, and when the polling transport fails, it kills the socket and makes the whole thing as a failure without checking the websocket connection.

It seems like it would be better to be able to continue to use the websocket connection. 

Thanks

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
