### ISSUE TITLE
Websocket connection closed with 1001 when high loading (1M messaging)

### ISSUE THREAD

**Issue by jumperchen** [socketio/engine.io-client-java#86]
We found that [okhttp](https://github.com/square/okhttp) websocket client implementation is not stable when sending with 1M messages. (refer to this issue - https://github.com/square/okhttp/issues/3317)
Other Java implementation seem to be more stable. Like [Tyrus](https://tyrus.java.net/), [NV-Websocket-Client](https://github.com/TakahikoKawasaki/nv-websocket-client)).

So it would be better if you could provide a way to switch the Java client implementation.

**Comment by b95505017** [comment]
Please checkout #85, you could implement your own WebSocket.Factory interface now.

**Comment by jumperchen** [comment]
Thanks, I will try with that mechanism. (I tested by hard code with NV-Websocket-Client, it works well without any issue :) )

**Comment by jumperchen** [comment]
@b95505017 
Do you know about the schedule when the 0.8.4 version will be released? (about the fixed of #85)

**Comment by b95505017** [comment]
I don't have the permission to release, must discuss with @nkzawa .
