### ISSUE TITLE
Polling broken with android 0.8.3 and server >= 2.1.0

### ISSUE THREAD

**Issue by sloops77** [socketio/engine.io-client-java#88]
We upgrade the engine.io servers from 2.0.2 to 2.1.0 at which point xhr polling transport stopped working for android (v0.8.3). After the first messages are exchanged an error is raised by the client side when the first large message arrives from the server. This causes a disconnection. This is true for all versions of the server up to 3.1.0

The received message looks like it's a short binary message that the android library cannot decode.

it may be related to this change in the parser https://github.com/socketio/engine.io-parser/pull/85

We will keep investigating

**Comment by baytsif** [comment]
following @sloops77, from client (android) side perspective,  we're using the java client (0.8.3). after sending the first message through the socket, Socket.EVENT_ERROR callback is being called, followed by Socket.EVENT_CLOSE, with message "transport error" and "parser error".

**Comment by nkzawa** [comment]
Update coming 👍 

https://github.com/socketio/engine.io-client-java/pull/93
