### ISSUE TITLE
Send custom headers

### ISSUE THREAD

**Issue by csoni111** [socketio/engine.io-client-java#89]
How to send custom headers from the java client as mentioned [here](https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders) in the docs?

**Comment by nkzawa** [comment]
We don't have `extraHeaders` option for Java client, but you can do the same thing like https://github.com/socketio/engine.io-client-java#accessing-http-headers

**Comment by juniorfrogie** [comment]
@nkzawa I cannot get this code works,

private Socket mSocket;
{
    try {
        IO.Options opts = new IO.Options();
        mSocket = IO.socket(socket_url, opts);
        mSocket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {

                Transport transport = (Transport)args[0];
                transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                        @SuppressWarnings("unchecked")
                        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
                        // modify request headers
                        headers.put("x-user-id", Arrays.asList("5B59F68B7B7811E88C3E52964BF487E4"));
                    }
                }).on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
                    @Override
                    public void call(Object... args) {
                    }
                });
            }
        });

    } catch (URISyntaxException e) {}
}
