### ISSUE TITLE
Cant find some fields in io.socket.engineio.client$Transport

### ISSUE THREAD

**Issue by invincibletrain** [socketio/engine.io-client-java#91]
im working on socketio and engineio libraries, the souce of socketio is working with engineio version 0.8.3. the binary gradle version of engineio is working fine while the source code on github is different a bit.
package io.socket.engineio.client;
class Transport

binary versio has:
public static class Options {
        public String hostname;
        public String path;
        public String timestampParam;
        public boolean secure;
        public boolean timestampRequests;
        public int port = -1;
        public int policyPort = -1;
        public Map<String, String> query;
        public SSLContext sslContext;
        public HostnameVerifier hostnameVerifier;
        protected Socket socket;
        public Proxy proxy;
        public String proxyLogin;
        public String proxyPassword;
    }

source code on github:
public static class Options {
        public String hostname;
        public String path;
        public String timestampParam;
        public boolean secure;
        public boolean timestampRequests;
        public int port = -1;
        public int policyPort = -1;
        public Map<String, String> query;
        protected Socket socket;
        public WebSocket.Factory webSocketFactory;
        public Call.Factory callFactory;
    }

**Comment by jimmymbiyu** [comment]
I am also experiencing the same issue. I am upgrading from v0.7.0 to v1.0.0 and the field `io.socket.engineio.client.Transport.Options#sslContext` is no longer available. I use the field in a method that trusts all SSL certificates, something we need for our test environment.
```
options.sslContext = SSLContext.getInstance("SSL");
options.sslContext.init(null, trustAllCerts, new SecureRandom());
```

How can I do this in v1.0.0?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
