### ISSUE TITLE
How to Send Custom Header in Android

### ISSUE THREAD

**Issue by ghost** [socketio/engine.io-client-java#97]
Convert this code in JAVA

iOS Swift code
` let manager =  SocketManager(socketURL: URL(string: "http://2de0c832.ngrok.io/")!, config: [.log(true), .compress, .extraHeaders(["Authorization": "Bearer \(Defaults[.authToken])"])])`

**Comment by juniorfrogie** [comment]
Do you find way to do it yet? I'm stuck at this too.

**Comment by hasankucuk** [comment]
@KonstantinBerkow Thanks. After five hours of work, the problem was solved. :) 👍

**Comment by darrachequesne** [comment]
According to the README, you can add a custom header with:

```java
socket.on(Socket.EVENT_TRANSPORT, new Emitter.listener() {
  @Override
  public void call(Object... args) {
    // Called on a new transport created.
    Transport transport = (Transport)args[0];

    transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
      @Override
      public void call(Object... args) {
        @SuppressWarnings("unchecked")
        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
        headers.put("Authorization", Arrays.asList("Bearer xxxx"));
      }
    });
  }
});
```

But based on the number of questions around this, I think it might make sense to add a `headers` map in the `Socket.Options` object.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-client-java/commit/dfe65e3b3b5eab4c3fddb9dfbf53d684fe461043.
